cache:
  paths:
    - ".next/cache"

steps:
  - label: ":lint: Lint"
    command: |

      echo "--- Before build"
      du -sh .next/cache || echo "No cache directory found"

      echo "--- Install and build"
      npm install
      npm run lint

      echo "--- After build"
      du -sh .next/cache || echo "No cache directory found"

  - label: ":wrench: Build"
    command: |

      echo "--- Before build"
      du -sh .next/cache || echo "No cache directory found"

      echo "--- Install and build"
      npm install
      npm run build

      echo "--- After build"
      du -sh .next/cache || echo "No cache directory found"
