# cache:
#   paths:
#     - .nextjs/cache
#     - node_modules

steps:
  - label: ":lint-roller: Lint"
    command: |
      npm install
      npm run lint
    cache:
      - .nextjs/cache
      - node_modules

  - label: ":hammer: Build"
    command: |
      npm install
      npm run build
    cache:
      - .nextjs/cache
      - node_modules
